//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace laba10subd
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderView
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> Дата_заказа { get; set; }
        public string Покупатель { get; set; }
        public Nullable<int> Количество { get; set; }
        public string Товар { get; set; }
        public string Доставка { get; set; }
    }
}
