//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace laba10subd
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductView
    {
        public int ID { get; set; }
        public string Название { get; set; }
        public string Поставщик { get; set; }
        public string Категория { get; set; }
        public string Единица_измерения { get; set; }
    }
}
