//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace laba10subd
{
    using System;
    using System.Collections.Generic;
    
    public partial class SupplierView
    {
        public int ID { get; set; }
        public string Название { get; set; }
        public string Адрес { get; set; }
        public string Город { get; set; }
        public string Телефон { get; set; }
        public string Почта { get; set; }
    }
}
